name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      env:
        GITHUB_TOKEN: c917ebb597bea4ae490d31a5760c8d3082846ca5
        GITHUB_USERNAME: repplix
        GITHUB_ACTOR: repplix  
      run: |
        cat ~/.m2/settings.xml
        cat .github/workflows/settings.xml
        mvn --settings .github/workflows/settings.xml clean install
        
