name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup environment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: x-access-token
      run: | 
        echo "<settings><servers><server><id>github</id><username>${env.GITHUB_TOKEN}</username><password>${env.GITHUB_TOKEN }</password></server></servers></settings>" > ~/.m2/settings.xml
    - name: Build with Maven
      run: 
        mvn -B package --file pom.xml
        
