name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
            
    - name: Maven build      
      env:
        GITHUB_USERNAME2: ${{ secrets.GITHUB_USERNAME2 }}  
        GITHUB_TOKEN2: ${{ secrets.GITHUB_TOKEN2 }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B package --file pom.xml
    
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: mvn deploy
      
    - name: sonarqube update
      env:
        GITHUB_USERNAME2: ${{ secrets.GITHUB_USERNAME2 }}
        GITHUB_TOKEN2: ${{ secrets.GITHUB_TOKEN2 }}
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}        
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml sonar:sonar

