name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
            
    - name: Maven build
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME2 }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }}
        
      run: mvn -B package --file pom.xml
